
export  const SET_CURRENTINDEX ='SET_CURRENTINDEX';
export  const GET_CURRENTINDEX ='GET_CURRENTINDEX';
export  const SET_SONGLIST = 'SET_SONGLIST';
export  const GET_SONGLIST = 'GET_SONGLIST';
export  const SET_PLAYING = 'SET_PLAYING';
export  const SET_FULLSCREEN =  'SET_FULLSCREEN';
export  const SET_CURRENTSONG='SET_CURRENTSONG';
export  const SET_SEARCHHISTORY='SET_SEARCHHISTORY';
export  const SET_MINICLASS = 'SET_MINICLASS';